### ISSUE TITLE
nepi_jano_0.10.0 does not work on Chrome Version 40.0.2214.115 m

### ISSUE THREAD

**Issue by petermisovic** [ejci/nepi-jano#17]
Extension does not work because extension didn't come from the Chrome Web Store (https://support.google.com/chrome/answer/2811969?p=ui_remove_non_cws_extensions&rd=1&hl=en).

**Comment by ejci** [comment]
?

**Comment by petermisovic** [comment]
If I follow installation instructions, the extension is installed successfully. But after a short time Chrome informs me about blocked extension. Please, see https://dl.dropboxusercontent.com/u/89955594/nepi_jano_0.10.0.crx.jpg. Learn more link takes you to google's explanation https://support.google.com/chrome/answer/2811969?p=ui_remove_non_cws_extensions&rd=1&hl=en

**Comment by ejci** [comment]
`If you see a message saying "Extensions Disabled," it's because one or more of your extensions have been turned off to make Chrome safer. The extensions didn't come from the Chrome Web Store or were installed without your permission.`
This extension is not in chrome store and it will never be. There is also alternative way to install it (see instructions.

**Comment by petermisovic** [comment]
My fault, yes it is working. Sorry.
